#! /bin/sh

sxhkd &

bspc monitor -d term web music chat 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Background
feh --bg-fill ~/Pictures/monokai.jpg

# Polybar
$HOME/.config/polybar/launch.sh

# Compton
compton
