require("fzf-lua").setup({})

local map = vim.keymap.set
map("n", "<leader>ff", function()
	require("fzf-lua").files()
end, { desc = "Find Files" })
map("n", "<leader>fg", function()
	require("fzf-lua").git_files()
end, { desc = "Git Files" })
map("n", "<leader>fw", function()
	require("fzf-lua").git_worktrees()
end, { desc = "Git Worktrees" })
map("n", "<leader>fs", function()
	require("fzf-lua").live_grep()
end, { desc = "Live Grep" })
map("n", "<leader>fb", function()
	require("fzf-lua").buffers()
end, { desc = "Buffers" })
map("n", "<leader>fh", function()
	require("fzf-lua").help_tags()
end, { desc = "Help Tags" })
map("n", "<leader>fr", function()
	require("fzf-lua").lsp_references()
end, { desc = "Lsp References" })
map("n", "<leader>fo", function()
	require("fzf-lua").oldfiles()
end, { desc = "Recent Files" })
map("n", "<leader>fd", function()
	require("fzf-lua").diagnostics_document()
end, { desc = "Document Diagnostics" })
map("n", "<leader>fD", function()
	require("fzf-lua").diagnostics_workspace()
end, { desc = "Workspace Diagnostics" })
map("n", "<leader>fk", function()
	require("fzf-lua").keymaps()
end, { desc = "Keymaps" })
map("n", "<leader>fl", function()
	require("fzf-lua").blines()
end, { desc = "Buffer Lines" })
map("n", "<leader>fS", function()
	require("fzf-lua").git_status()
end, { desc = "Git Status" })
map("n", "<leader>fR", function()
	require("fzf-lua").resume()
end, { desc = "Resume Last Picker" })
