require("fzf-lua").setup({})

local map = vim.keymap.set
map("n", "<leader>ff", function()
	require("fzf-lua").files()
end, { desc = "Find Files" })
map("n", "<leader>fg", function()
	require("fzf-lua").git_files()
end, { desc = "Git Files" })
map("n", "<leader>fw", function()
	require("fzf-lua").git_worktrees()
end, { desc = "Git Worktrees" })
map("n", "<leader>fs", function()
	require("fzf-lua").live_grep()
end, { desc = "Live Grep" })
map("n", "<leader>fb", function()
	require("fzf-lua").buffers()
end, { desc = "Buffers" })
map("n", "<leader>fh", function()
	require("fzf-lua").help_tags()
end, { desc = "Help Tags" })
map("n", "<leader>fr", function()
	require("fzf-lua").lsp_references()
end, { desc = "Lsp References" })
